import { redirect, type Handle } from "@sveltejs/kit";
import { pageToMarkdown } from "$lib/server/html-to-md";

// Permanent redirects from retired URLs. Keys are the old path (exact match,
// no trailing slash). If the target moves again, update here. 301 is
// deliberate over 302 so link-equity and social card caches migrate.
const PERMANENT_REDIRECTS: Record<string, string> = {
  "/blog/introducing-crucible": "/blog/introducing-glassmkr",
  // The vertical pages were reorganised from AUDIENCES to USE CASES on 2026-08-03.
  // An SRE and a self-hoster running the same array need the same alert set, so
  // those two pages were near-duplicates with no product difference behind them.
  // What you run does change the rule set, so storage, compute and GPU are now the
  // split. Both retired pages were indexed, so they redirect rather than 404, and
  // both land on compute because that is the closest fit for a general fleet.
  "/for-sre": "/for-compute",
  // The tier-gating docs page documented the retired Free/Pro split; the
  // concept is gone, so the page is too. Indexed URL, hence 301 not 404.
  "/docs/api/tier-gating": "/docs/api",
  "/for-self-hosted": "/for-compute",
};

// In-memory cache of generated Markdown twins, keyed by target path. Marketing
// content changes only on deploy, which restarts the process and clears this,
// so it needs no TTL; it is bounded by the number of marketing routes.
const mdCache = new Map<string, string>();

// Map a `<path>.md` request to the page path it twins, or null if it is not a
// twin we serve. `/docs/<slug>.md` are shipped as static files (generated by
// scripts/docs-md.mjs) and served before this hook in production, so skip them.
function mdTargetPath(pathname: string): string | null {
  if (!pathname.endsWith(".md")) return null;
  // Reject a protocol-relative path (`//host/x.md`). event.url.pathname is
  // normally single-slash-rooted, but a raw request line `GET //evil.com/x.md`
  // arrives here verbatim (no route matched, so no trailing-slash normalize),
  // and `new URL("//evil.com/x", base)` at the fetch site resolves cross-origin
  // -> the server would issue an outbound GET to an attacker host (SSRF). The
  // backslash check is redundant (the URL parser folds `\` to `/`) but explicit.
  if (pathname.startsWith("//") || pathname.includes("\\")) return null;
  if (pathname === "/index.md") return "/";
  if (pathname.startsWith("/docs/")) return null;
  const target = pathname.slice(0, -".md".length);
  if (target.endsWith(".md")) return null;
  return target;
}

// The HTML pages carry their discovery relations in <head>. A Markdown twin has
// no head, so a client that fetched the .md directly, which is the whole point
// of the twins, previously had no way to find the LLM index or the API contract
// from it. Same relations, carried in the HTTP header instead.
//
// This covers twins generated ON DEMAND. The pre-generated ones under static/
// are served by adapter-node's sirv handler before this hook ever runs, so they
// get the same header from nginx (infrastructure/nginx/sites/glassmkr.com). Two
// places for one header is not ideal; one of them cannot see the request at
// all, which is the reason.
const DISCOVERY_LINK = [
  '<https://glassmkr.com/llms.txt>; rel="describedby"; type="text/plain"',
  '<https://app.glassmkr.com/api/openapi.json>; rel="service-desc"; type="application/vnd.oai.openapi+json"',
].join(", ");

function markdownResponse(md: string, canonicalPath?: string): Response {
  const link = canonicalPath
    ? `<https://glassmkr.com${canonicalPath}>; rel="canonical", ${DISCOVERY_LINK}`
    : DISCOVERY_LINK;
  return new Response(md, {
    headers: {
      "content-type": "text/markdown; charset=utf-8",
      "cache-control": "public, max-age=3600",
      "x-content-type-options": "nosniff",
      link,
    },
  });
}

export const handle: Handle = async ({ event, resolve }) => {
  const redirectTarget = PERMANENT_REDIRECTS[event.url.pathname];
  if (redirectTarget) {
    throw redirect(301, redirectTarget);
  }

  // Markdown twin of any marketing page: fetch the rendered HTML internally
  // and convert its <main> region. An agent that appends `.md` to a URL (or
  // follows the <link rel="alternate" type="text/markdown"> in the head) gets
  // clean Markdown without executing the page's JavaScript.
  const mdTarget = event.request.method === "GET" ? mdTargetPath(event.url.pathname) : null;
  if (mdTarget !== null) {
    const cached = mdCache.get(mdTarget);
    if (cached !== undefined) return markdownResponse(cached, mdTarget);

    // Defence in depth: never let the internal twin fetch leave this origin,
    // even if mdTargetPath is ever loosened. (mdTargetPath already rejects the
    // known `//host` vector above.)
    if (new URL(mdTarget, event.url.origin).origin !== event.url.origin) {
      return resolve(event);
    }

    try {
      const pageRes = await event.fetch(mdTarget, { headers: { accept: "text/html" } });
      const contentType = pageRes.headers.get("content-type") ?? "";
      if (pageRes.ok && contentType.includes("text/html")) {
        const html = await pageRes.text();
        const canonical = `https://glassmkr.com${mdTarget === "/" ? "" : mdTarget}`;
        const md = pageToMarkdown(html, canonical);
        if (md) {
          mdCache.set(mdTarget, md);
          return markdownResponse(md, mdTarget);
        }
      }
    } catch (err) {
      // A render/convert failure on one page must not 500 its `.md` URL;
      // fall through to the normal response (a 404) instead.
      console.error(`[md-twin] ${mdTarget}: ${err instanceof Error ? err.message : err}`);
    }
    // No twin (404, non-HTML, empty conversion, or error): fall through so the
    // `.md` path gets the normal response (a 404 for a page that does not exist).
  }

  const response = await resolve(event);
  // Security response headers (audit 2026-05-22 §1.6 / catalog T-309).
  // Fetch-directive CSP is set via kit.csp (svelte.config.js); these are
  // the header-only protections meta CSP cannot express.
  response.headers.set("X-Frame-Options", "DENY");
  response.headers.set("X-Content-Type-Options", "nosniff");
  response.headers.set("Referrer-Policy", "strict-origin-when-cross-origin");
  return response;
};
