// Read-only public-demo access policy.
//
// The demo customer row carries is_demo = true (migration 024); a demo
// visitor sees the real dashboard but must not change anything. The chokepoint
// in hooks.server.ts (demoGuard) consults this pure policy so the decision is
// unit-tested in isolation rather than entangled with the hook (which also
// wires module-load side effects).
//
// GET/HEAD/OPTIONS are allowed by default (the demo browses the real UI
// read-only). The exception is a short list of SIDE-EFFECTING GETs: browser
// redirect flows that write to the DB or call a payment provider (e.g. the
// Stripe checkout link, which creates a Stripe customer + checkout session and
// writes customers.stripe_customer_id). Those are denied even though they are
// GETs. Keep DEMO_BLOCKED_GETS in sync with any new write-on-GET handler.
//
// Mutations (POST/PUT/PATCH/DELETE) are denied except the unauthenticated
// demo lead-capture endpoint, which a demo visitor legitimately submits, and the
// ticket-draft generator (see DEMO_ALLOWED_MUTATION_PATTERNS): it is a POST only
// by REST convention; it does not mutate customer state. It reads the alert the
// visitor is already looking at, builds a plain-text provider message from a
// deterministic template (no LLM call, no third-party network), and returns it.
// The only write is an internal audit row, which the lead endpoint also produces.
// So it is safe for the read-only demo and lets a visitor try the feature.

const SAFE_METHODS = new Set(["GET", "HEAD", "OPTIONS"]);

// Mutating endpoints (exact pathnames) a demo session is allowed to reach.
const DEMO_ALLOWED_MUTATIONS = new Set(["/api/v1/demo/lead"]);

// POST endpoints with dynamic path params a demo session is allowed to reach.
// The ticket-draft route is read-scoped (no customer-state mutation); see above.
// POST-only on purpose: that route implements no other verb, so allowing only
// POST keeps the demo allowance least-privilege (a stray DELETE/PUT stays blocked).
const DEMO_ALLOWED_POST_PATTERNS = [
  /^\/api\/v1\/servers\/[^/]+\/alerts\/[^/]+\/ticket-draft$/,
];

// Side-effecting GETs a demo session must NOT reach (they write or charge).
const DEMO_BLOCKED_GETS = new Set([
  "/api/v1/billing/checkout",
  // The audit log is not side-effecting, but it is the one read that leaks other
  // people. The demo is a SHARED tenant, so its audit rows are generated by
  // whoever is browsing the demo right now, and the API returns source_ip and
  // user_agent per row. That meant any visitor could read every other visitor's
  // IP address and browser on the page whose whole job is to argue we can be
  // trusted with your infrastructure. Blocked at the same chokepoint as the
  // mutations rather than by redacting fields, because a redaction is one
  // forgotten column away from leaking again.
  "/api/v1/account/audit",
  "/settings/audit",
]);

export type DemoDisposition = "allow" | "block-mutation" | "block-get";

/**
 * Decide how the demo guard should treat a request from a demo session.
 *   "allow"          : let it through (read-only browsing, or the lead POST)
 *   "block-get"      : a side-effecting GET; the guard should bounce it with a
 *                      redirect (it is a browser navigation)
 *   "block-mutation" : a disallowed state-changing method; the guard returns 403
 */
export function demoDisposition(method: string, pathname: string): DemoDisposition {
  if (SAFE_METHODS.has(method)) {
    return DEMO_BLOCKED_GETS.has(pathname) ? "block-get" : "allow";
  }
  if (DEMO_ALLOWED_MUTATIONS.has(pathname)) return "allow";
  if (method === "POST" && DEMO_ALLOWED_POST_PATTERNS.some((re) => re.test(pathname))) return "allow";
  return "block-mutation";
}
